name: terraform deployment 

on: 
  push: 
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  terraform:
    runs-on: ubuntu-latest

#cloning the repository
    steps:
      - name: checkout respository 
        uses: actions/checkout@v3


# installing terraform
      - name: set up terraform
        uses: harshicorp/setup-terraform@v3
        with:
           terraform_version: "1.8.5"

      - name: initialising terraform 
        run: terraform init 

      - name: validate terraform 
        run: terraform validate 

      - name: plan
        run: terraform plan

      - name: apply terraform
        run: terraform apply
        
  