name: terraform deployment 

on: 
  push: 
    branches:
      - master  
  pull_request:
    branches:
      - master

          
jobs:
  terraform:
    runs-on: ubuntu-latest

#cloning the repository
    steps:
      - name: checkout respository 
        uses: actions/checkout@v3
        
# installing terraform
      - name: set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "1.8.5"
           
      - name: configure aws creds
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | 
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV

      - name: initialising terraform 
        run: terraform init 

      - name: validate terraform 
        run: terraform validate 

      - name: plan
        run: terraform plan

      - name: apply terraform
        run: terraform apply
        
  