name: terraform deployment 

on: 
  push: 
    branches:
      - master  
  pull_request:
    branches:
      - master
env: 
  aws_access_key_id: "${{ secrets.ACCESS_KEY_ID }}"
  aws_secret_access_key:  "${{ secrets.SECRET_ACCESS_KEY }}"

jobs:
  terraform:
    runs-on: ubuntu-latest

#cloning the repository
    steps:
      - name: checkout respository 
        uses: actions/checkout@v3


# installing terraform
      - name: set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
           terraform_version: "1.8.5"

      - name: initialising terraform 
        run: terraform init 

      - name: validate terraform 
        run: terraform validate 

      - name: plan
        run: terraform plan

      - name: apply terraform
        run: terraform apply
        
  